[project]
name = "python-template"
version = "0.1.0"
description = "A movie forwarding bot made for the users of Mollywood Diaries"
authors = ["Akash Kiran T"]
requires-python = ">=3.11"
dependencies = []
